### ISSUE TITLE
Wire Tool not working

### ISSUE THREAD

**Issue by Shadow-Genesis** [OCB7D2D/ElectricityOverhaul#12]
I am running a dedicated server. When ever we switch to our wire tool we get an error, "NULL Reference", pop up in the in-game terminal. A friend has told me he has to logout and back in to get a single use out of the tool. I wish I could be more helpful as this is a great mod.

Screenshot of error: https://cdn.discordapp.com/attachments/960903522893856808/1017464295291891834/7_Days_To_Die_08_09_2022_16_59_16.png (Too large to upload.)

**Comment by mgreter** [comment]
Screenshots of errors are unfortunately useless, I'd need the real error log to deduct anything from it (as it will contain stack traces that at least give a hint were the error is happening). I'll keep this report open for a little to see if others have the same issue, as so far you're the first to report this. Otherwise I can't do much from what you've posted, sorry.
