### ISSUE TITLE
Error parsing configfile [A20]

### ISSUE THREAD

**Issue by Fuggschen** [OCB7D2D/ElectricityOverhaul#3]
Hello,

we are trying to run your mod in version A20 with an already progressed savegame. I tried to add the config values like you described in the readme, but the server returns following error:
```
2021-12-25T01:37:06 0.459 ERR ====================================================================================================
2021-12-25T01:37:06 0.459 ERR Error parsing configfile property 'LoadVanillaMap': Could not parse config value 'true'
2021-12-25T01:37:06 0.459 INF Make sure your configfile is updated the current server version!
2021-12-25T01:37:06 0.459 INF Startup aborted due to the given error in server configfile
2021-12-25T01:37:06 0.459 ERR ====================================================================================================
```

The config file looks like this (didn't added the full config because its irrelevant):
```
<ServerSettings>
  [settings]
  <property name="LoadVanillaMap" value="true" />
  <property name="BatteryPowerPerUse" value="25" />
  <property name="MinPowerForCharging" value="20" />
  <property name="FuelPowerPerUse" value="750" />
  <property name="PowerPerPanel" value="30" />
  <property name="PowerPerEngine" value="50" />
  <property name="PowerPerBattery" value="50" />
  <property name="ChargePerBattery" value="35" />
</ServerSettings>
```

Also your modpage says that the following mods are included in the main mod, but as far as I know, there are not:
* Electricity Wire Colors (A20/BepInEx)
* Electricity Workarounds (A20)
* Electricity No Wires (A20)
* Electricity Solar Recipes (XML)

Do I have to install them seperatly or will they be included in future updates?

**Comment by mgreter** [comment]
Thanks for the bug report @Fuggschen, it seems that this mod does have some issues with dedicated servers, and how you wrote in your report I suspect you and you're buddies are trying it on a dedicated server? First, no, the mentioned additional mods are not included in the overhaul mod. Pick the ones you like and leave out the ones you don't (and sorry, but docs are a bit out of sync since the A20 upgrade frenzy).

In order to improve multiplayer I unfortunately need the help of volunteers, so if you would be willing to dedicate some of your time to help me debug it, just give me your discord name. My main conclusion why this mod may not work is the BepInEx dependency, which I don't know if only the server or also every client needs. It seemed to work in A19. But a lot has changed with A20, so I might be able to reproduce it. But this will need some time to properly investigate (so any help is appreciated).

**Comment by Fuggschen** [comment]
Hey @mgreter, yes we are running your mod on our dedicated server and I would love to help you with that. My Discord name is Fuggschen#2306. Just add me and we can try to debug this.

And thanks for the info with the optional mods. I just installed them and they work great!

**Comment by mgreter** [comment]
Could you tell me if you are using a windows or linux server?
Windows may work but linux probably needs a few more tweaks.

**Comment by Fuggschen** [comment]
We are actually using both. First tested it under linux but switched then to windows because I saw that this was definitely made for windows

**Comment by mgreter** [comment]
I updated the repo today to add linux compatibility and also fixed a few other bugs:
https://github.com/OCB7D2D/ElectricityOverhaul/archive/master.zip
There is no official new version yet, so please test it out!
Re-open if you believe your issue is still there.

**Comment by Fuggschen** [comment]
Just removed the old version and tried this out but it is still not possible to add the arguments into the ServerSettings like I described in my first post. So there is no option for me to change the power settings on the dedicated server

**Comment by mgreter** [comment]
Could you tell me if you tried it on win or nix server?

**Comment by Fuggschen** [comment]
Tested it on Windows Server
